apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: biblioteca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-app # Nombre del contenedor
          image: ewdeve/pgbackend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: mysql-svc
            - name: DB_PORT
              value: "3306"
            - name: DB_URL
              value: "jdbc:mysql://mysql-svc:3306/biblioteca1?useSSL=false&serverTimezone=UTC"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-password