apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: biblioteca
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP