apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: biblioteca
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000 # Puerto svc
      targetPort: 8000 # Puerto del contenedor del Pod
  type: LoadBalancer