apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: biblioteca
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: biblioteca.example.com
    http:
      paths:
      - backend:
          service:
            name: backend-svc
            port:
              number: 8000
        path: /biblioteca1/v1(/|$)(.*) # Esta ruta ahora se pasará intacta al backend
        pathType: Prefix
      - backend:
          service:
            name: frontend-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  - http: # Esta es la regla sin host, para la IP directa
      paths:
      - backend:
          service:
            name: frontend-svc
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: backend-svc
            port:
              number: 8000
        path: /biblioteca1/v1(/|$)(.*) # Esta ruta también se pasará intacta al backend
        pathType: Prefix