apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: biblioteca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: ewdeve/pgweb:50684c1
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_API_URL
              value: "http://backend-svc:8000/biblioteca1/v1"