spec:
  rules:
  - host: biblioteca.example.com  # <--- Solo coincide con este host
    http:
      paths:
      - backend:
          service:
            name: backend-svc
            port:
              number: 8000
        path: /biblioteca1/v1(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: frontend-svc
            port:
              number: 80
        path: /
        pathType: Prefix